version: '2'

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - myInfluxVolume:/var/lib/influxdb2

volumes:
  myInfluxVolume:
